# (c) https://github.com/MontiCore/monticore

image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk11

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - "gradle build $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
      - "target/"
      - ".gradle/"
    expire_in: 1 week


deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "gradle publish -PmavenPassword=$pass -PmavenUser=$user $GRADLE_OPT $ARGS2"
  artifacts:
    paths:
      - target/libs/MCUCD.jar
    expire_in: 1 week
  only:
    refs:
      - develop